$schema: https://git.drupalcode.org/project/drupal/-/raw/HEAD/core/assets/schemas/v1/metadata.schema.json
name: Production Check
description: A code block entry for the production checklist section.
status: experimental
props:
  type: object
  properties:
    header:
      type: string
      title: Block Header
      default: 'php.ini + deploy'
    code:
      type: string
      title: Code Content
      description: 'The code/config block content.'
      pattern: '(.|\r?\n)*'
